vich_uploader:
    db_driver: orm

    mappings:
        images_in_vich_uploader:
            uri_prefix: '%app.path.images%'
            namer: Vich\UploaderBundler\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.images%'
